name: Testing Workflow Variables
on: 
  workflow_dispatch:
env: 
  cloud: google-cloud
jobs: 
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Kannan! it's Monday"
        run: echo "$Greeting $First_Name is using $cloud"
        env:
          First_Name: Azhagii
  greeting_job2:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Kannan! it's Tuesday"
        run: echo "${{ vars.Greetings_1 }} $ {{ vars.First_Name_1 }} is using $cloud
